VOCAB_SIZE = None

CONTEXT_LENGTH = 64
EMBEDDING_DIM = 128
NUM_HEADS = 4
NUM_LAYERS = 2
DROPOUT = 0.1
BATCH_SIZE = 32
LEARNING_RATE = 3e-4
EPOCHS = 30
WEIGHT_DECAY = 1e-2

DATASET_STRIDE = CONTEXT_LENGTH   # now actually used, see dataset.py call below
MAX_BATCHES_PER_EPOCH = 600
PRINT_EVERY = 25
SAMPLE_FROM_K = 50

# --- new ---
WARMUP_STEPS = 200
GRAD_CLIP = 1.0
USE_AMP = True
SAVE_EVERY_EPOCH = True